name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  pages:
    name: mdbook build/test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: mdbook build and test
      run: |
        mdbook build
        mdbook test
